config/routes.rb
Rails.application.routes.draw do
  
  resources :airports
  resources :flights
  resources :bookings
  resources :passenger_bookings
  root 'flights#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passenger_bookings
  has_many :passengers, through: :passenger_bookings
  accepts_nested_attributes_for :passenger_bookings
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :bookings
  has_many :bookings, through: :passenger_bookings
end

app/models/passenger_booking.rb
class PassengerBooking < ApplicationRecord
  belongs_to :booking
  belongs_to :passenger
  accepts_nested_attributes_for :passenger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new 
    @booking = Booking.new(flight_id: params[:flight_id])
    params[:no_of_passengers].to_i.times { @booking.passenger_bookings.build.build_passenger }

    puts 'the booking details are'
    p params
    p @booking
  end

  def show 
    puts 'got here'
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking.flight_id)
    @arrival_airport = Airport.find(@flight.arrival_airport_id)
    @departure_airport = Airport.find(@flight.departure_airport_id)
  end

  def create 
    puts 'submitted params are'
    p params
    @booking = Booking.new(booking_params)
    if @booking.save! 
      redirect_to @booking, notice: 'The booking was successfully created'
    else  
      render :new, status: :unprocessable_entity 
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passenger_bookings_attributes: [ passenger_attributes: [:name, :email]])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all

    if params[:departure_airport_id].present?
      p params
      puts 'class is'
      departure_date = Date.new(
        params["[departure_date(1i)]"].to_i,
        params["[departure_date(2i)]"].to_i,
        params["[departure_date(3i)]"].to_i
      )
      @selected_departure_date = departure_date
      p params
      # departure_date = Date.new(
      #   params["departure_date(1i)"].to_i,
      #   params["departure_date(2i)"].to_i,
      #   params["departure_date(3i)"].to_i
      # )
      p departure_date
      # Extract the parameters
      departure_airport_id = params[:departure_airport_id]
      arrival_airport_id = params[:arrival_airport_id]
      number_of_passengers = params[:number_of_passengers]
      # departure_date = Date.parse(params[:departure_date])
  
      # departure_date = Date.new(params["departure_date(1i)"].to_i, params["departure_date(2i)"].to_i, params["departure_date(3i)"].to_i)

      # Query the flights based on the parameters
      @suitable_flights = Flight.where(
        departure_airport_id: departure_airport_id,
        arrival_airport_id: arrival_airport_id,
        departure_time: departure_date.beginning_of_day..departure_date.end_of_day
      )
      puts 'flight is'
      p @suitable_flights
    end
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  
end

app/controllers/passenger_bookings_controller.rb
class PassengerBookingsController < ApplicationController
  # def new
  #   @passenger_booking = Passenger_Booking.new(params)
  # end
end

app/controllers/passengers_controller.rb
class PassengerController < ApplicationController
  # def new 
  #   @passenger = Passenger.new(params)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passenger_bookings_helper.rb
module PassengerBookingsHelper
end

app/helpers/passenger_helper.rb
module PassengerHelper
end

app/views/bookings/new.html.erb
this is the new views
<% flash.each do |key, message| %>
  <%= key %>
  <%= message %>
<% end %>
 <%= form_with model: @booking do |b| %>
  <%= b.hidden_field :flight_id, value: params[:flight_id] %>

  <% @booking.passenger_bookings.each do |pb| %>
    <%= b.fields_for :passenger_bookings, pb do |pb_fields| %>
      <%= pb_fields.fields_for :passenger do |p| %>
        <div class="field">
          <%= p.label :name, 'Passenger Name:' %>
          <%= p.text_field :name %>
        </div>
        <div class="field">
          <%= p.label :email, 'Passenger Email:' %>
          <%= p.email_field :email %>
        </div>
      <% end %>
    <% end %>
  <% end %>

  <div class="actions">
    <%= b.submit %>
  </div>
<% end %>

app/views/bookings/show.html.erb
The booking details are 

<ul>
  <li>Flight no:</li>
  <li><%= @flight.id %></li>
  <li>Booking no:</li>
  <li><%= @booking.id %></li>
  <li>Arrival Airport:</li>
  <li><%= @arrival_airport.city %></li>
  <li>Departure Airport:</li>
  <li><%= @departure_airport.city %></li>
  <li>Departure time:</li>
  <li><%= @flight.departure_time %></li>
  <li>No of passengers:</li>
  <li><%= @booking.passenger_bookings.count %></li>
  <li>Passenger details:</li>
  <ul>
    <% @booking.passenger_bookings.each do |pb| %>
      <li>Name:</li>
      <li><%= pb.passenger.name %> </li>
      <li>Email:</li>
      <li><%= pb.passenger.email %></li>
    <% end %>
  </ul>

</ul>

app/views/flights/_inquire_flight.html.erb
<%= form_with url: flights_path, method: :get, local: true do |f| %>
  <%= f.label :departure_airpot, "Departure" %>
  <%= f.select(:departure_airport_id, Airport.all.map { |a| [a.city, a.id] }) %>
  <%= f.label :arrival_airport, "Arrival" %>
  <%= f.select(:arrival_airport_id, Airport.all.map { |a| [a.city, a.id] }) %>
  <%= label_tag :number_of_passengers, "Number of Passengers" %>
  <%= select_tag "number_of_passengers", options_for_select([1, 2, 3, 4]) %>
  <%= f.label :departure_date, "Date Of Departure" %>  
  <%# <%= select_tag 'departure_date', options_for_select(Flight.all.map { |f| [f.departure_time.strftime("%Y-%m-%d"), f.departure_time] }) %> %>
  <%= f.date_select :departure_date,
                         default: params[:departure_date].present? ? Date.parse(params[:departure_date]) : nil %>

  <%= f.submit "Submit" %>
<% end %>

app/views/flights/_inquired_flight.html.erb
<%= form_with url: flights_path, method: :get, local: true do |f| %>
  <%= f.label :departure_airpot, "Departure" %>
  <%= f.select :departure_airport_id, options_for_select(Airport.all.map { |a| [a.city, a.id] }, selected: params[:departure_airport_id]) %>
  <%= f.label :arrival_airport, "Arrival" %>
  <%= f.select:arrival_airport_id, options_for_select(Airport.all.map { |a| [a.city, a.id] }, selected: params[:arrival_airport_id]) %>
  <%= label_tag :number_of_passengers, "Number of Passengers" %>
  <%= select_tag :number_of_passengers, options_for_select([1, 2, 3, 4], selected: params[:number_of_passengers]) %>
  <%= f.label :departure_date, "Date Of Departure" %>  
  <%# <%= select_tag 'departure_date', options_for_select(Flight.all.map { |f| [f.departure_time.strftime("%Y-%m-%d"), f.departure_time] }, selected: Date.parse(params[:departure_date])) %> %>
  <%# <%= f.date_select :departure_date,
                        default: params[:departure_date].present? ? Date.parse(params[:departure_date]) : nil %> 
  <%= f.date_select :departure_date, include_blank: true, selected: @selected_departure_date.present? ? @selected_departure_date : nil %>
  <% puts 'debugiing' %>
  <% p params %>
  <% p params[:departure_date].present? %>
  
  <%# <%= f.date_select :departure_date, Flight.all.map(&:departure_time) %> %>
  <%= f.submit "Submit" %>
<% end %>

app/views/flights/create.html.erb
<h1>Flights#create</h1>
<p>Find me in app/views/flights/create.html.erb</p>

app/views/flights/destroy.html.erb
<h1>Flights#destroy</h1>
<p>Find me in app/views/flights/destroy.html.erb</p>

app/views/flights/edit.html.erb
<h1>Flights#edit</h1>
<p>Find me in app/views/flights/edit.html.erb</p>

app/views/flights/index.html.erb
<h1>Flights#index</h1>
<p>Find me in app/views/flights/index.html.erb</p>


<% if params[:departure_airport_id].present? %>
  <%= render 'inquired_flight' %>
  <ul>
    <%= form_with(url: new_booking_path, method: :get) do |form| %>
      <%  @suitable_flights.each do |flight| %>
        <li>
          <%= form.label(:flight_id, "Flight no #{flight.id}") %>
          <%= form.radio_button(:flight_id, flight.id) %>
          <%= form.hidden_field :no_of_passengers, value: params[:number_of_passengers] %>
        </li>
      <% end %>
      <%= form.submit("Submit") %>
    <% end %>
  </ul>

<% else %>
  <%= render 'inquire_flight' %>
<% end %>

app/views/flights/new.html.erb
<h1>Flights#new</h1>
<p>Find me in app/views/flights/new.html.erb</p>

app/views/flights/show.html.erb
<h1>Flights#show</h1>
<p>Find me in app/views/flights/show.html.erb</p>

app/views/flights/update.html.erb
<h1>Flights#update</h1>
<p>Find me in app/views/flights/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>